//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.13 at 06:41:27 PM MEZ 
//


package de.freebits.omt.core.xml.entities.patterns;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *     			Element-Typ zur Beschreibung eines Motives
 *     		
 * 
 * <p>Java class for nodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="note" type="{http://freebits.de/OMT-engine/schemas/Patterns}noteType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://freebits.de/OMT-engine/schemas/Patterns}idAttributeType" />
 *       &lt;attribute name="deltalength" use="required" type="{http://freebits.de/OMT-engine/schemas/Patterns}deltalengthAttributeType" />
 *       &lt;attribute name="length" use="required" type="{http://freebits.de/OMT-engine/schemas/Patterns}lengthAttributeType" />
 *       &lt;attribute name="beats-per-metre" use="required" type="{http://freebits.de/OMT-engine/schemas/Patterns}beatspermetreAttributeType" />
 *       &lt;attribute name="beatlength" use="required" type="{http://freebits.de/OMT-engine/schemas/Patterns}beatlengthAttributeType" />
 *       &lt;attribute name="deltatime-metre" use="required" type="{http://freebits.de/OMT-engine/schemas/Patterns}deltatimemetreAttributeType" />
 *       &lt;attribute name="min-tempo" use="required" type="{http://freebits.de/OMT-engine/schemas/Patterns}mintempoAttributeType" />
 *       &lt;attribute name="max-tempo" use="required" type="{http://freebits.de/OMT-engine/schemas/Patterns}maxtempoAttributeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nodeType", propOrder = {
    "note"
})
public class NodeType {

    protected List<NoteType> note;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "deltalength", required = true)
    protected float deltalength;
    @XmlAttribute(name = "length", required = true)
    protected float length;
    @XmlAttribute(name = "beats-per-metre", required = true)
    protected BigInteger beatsPerMetre;
    @XmlAttribute(name = "beatlength", required = true)
    protected float beatlength;
    @XmlAttribute(name = "deltatime-metre", required = true)
    protected float deltatimeMetre;
    @XmlAttribute(name = "min-tempo", required = true)
    protected BigInteger minTempo;
    @XmlAttribute(name = "max-tempo", required = true)
    protected BigInteger maxTempo;

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoteType }
     * 
     * 
     */
    public List<NoteType> getNote() {
        if (note == null) {
            note = new ArrayList<NoteType>();
        }
        return this.note;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the deltalength property.
     * 
     */
    public float getDeltalength() {
        return deltalength;
    }

    /**
     * Sets the value of the deltalength property.
     * 
     */
    public void setDeltalength(float value) {
        this.deltalength = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public float getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(float value) {
        this.length = value;
    }

    /**
     * Gets the value of the beatsPerMetre property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBeatsPerMetre() {
        return beatsPerMetre;
    }

    /**
     * Sets the value of the beatsPerMetre property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBeatsPerMetre(BigInteger value) {
        this.beatsPerMetre = value;
    }

    /**
     * Gets the value of the beatlength property.
     * 
     */
    public float getBeatlength() {
        return beatlength;
    }

    /**
     * Sets the value of the beatlength property.
     * 
     */
    public void setBeatlength(float value) {
        this.beatlength = value;
    }

    /**
     * Gets the value of the deltatimeMetre property.
     * 
     */
    public float getDeltatimeMetre() {
        return deltatimeMetre;
    }

    /**
     * Sets the value of the deltatimeMetre property.
     * 
     */
    public void setDeltatimeMetre(float value) {
        this.deltatimeMetre = value;
    }

    /**
     * Gets the value of the minTempo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinTempo() {
        return minTempo;
    }

    /**
     * Sets the value of the minTempo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinTempo(BigInteger value) {
        this.minTempo = value;
    }

    /**
     * Gets the value of the maxTempo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxTempo() {
        return maxTempo;
    }

    /**
     * Sets the value of the maxTempo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxTempo(BigInteger value) {
        this.maxTempo = value;
    }

}
