//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.07 at 10:07:24 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://freebits.de/OMT-engine/schemas/MotivEXtraction", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.freebits.omt.core.xml.entities.motifextraction;
