//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.07 at 10:07:24 AM MEZ 
//


package de.freebits.omt.core.xml.entities.motifextraction;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Motivbeschreibung
 * 
 * <p>Java class for pattersNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pattersNodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://freebits.de/OMT-engine/schemas/MotivEXtraction}nodeType">
 *       &lt;sequence>
 *         &lt;element name="note" type="{http://freebits.de/OMT-engine/schemas/MotivEXtraction}noteType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tempo" use="required" type="{http://freebits.de/OMT-engine/schemas/MotivEXtraction}tempoAttributeType" />
 *       &lt;attribute name="beats-per-metre" use="required" type="{http://freebits.de/OMT-engine/schemas/MotivEXtraction}beatsPerMetreAttributeType" />
 *       &lt;attribute name="beatlength" use="required" type="{http://freebits.de/OMT-engine/schemas/MotivEXtraction}beatlengthAttributeType" />
 *       &lt;attribute name="deltatime-metre" use="required" type="{http://freebits.de/OMT-engine/schemas/MotivEXtraction}deltatimeMetreAttributeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pattersNodeType", propOrder = {
    "note"
})
public class PattersNodeType
    extends NodeType
{

    protected List<NoteType> note;
    @XmlAttribute(name = "tempo", required = true)
    protected BigInteger tempo;
    @XmlAttribute(name = "beats-per-metre", required = true)
    protected int beatsPerMetre;
    @XmlAttribute(name = "beatlength", required = true)
    protected float beatlength;
    @XmlAttribute(name = "deltatime-metre", required = true)
    protected float deltatimeMetre;

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoteType }
     * 
     * 
     */
    public List<NoteType> getNote() {
        if (note == null) {
            note = new ArrayList<NoteType>();
        }
        return this.note;
    }

    /**
     * Gets the value of the tempo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTempo() {
        return tempo;
    }

    /**
     * Sets the value of the tempo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTempo(BigInteger value) {
        this.tempo = value;
    }

    /**
     * Gets the value of the beatsPerMetre property.
     * 
     */
    public int getBeatsPerMetre() {
        return beatsPerMetre;
    }

    /**
     * Sets the value of the beatsPerMetre property.
     * 
     */
    public void setBeatsPerMetre(int value) {
        this.beatsPerMetre = value;
    }

    /**
     * Gets the value of the beatlength property.
     * 
     */
    public float getBeatlength() {
        return beatlength;
    }

    /**
     * Sets the value of the beatlength property.
     * 
     */
    public void setBeatlength(float value) {
        this.beatlength = value;
    }

    /**
     * Gets the value of the deltatimeMetre property.
     * 
     */
    public float getDeltatimeMetre() {
        return deltatimeMetre;
    }

    /**
     * Sets the value of the deltatimeMetre property.
     * 
     */
    public void setDeltatimeMetre(float value) {
        this.deltatimeMetre = value;
    }

}
