//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.05 at 06:04:42 PM MEZ 
//


package de.freebits.omt.core.xml.entities.leadsheets;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Liste aller Leadsheets
 *     		
 * 
 * <p>Java class for leadsheetsNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leadsheetsNodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="leadsheet" type="{http://freebits.de/OMT-engine/schemas/Leadsheets}leadsheetNodeType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leadsheetsNodeType", propOrder = {
    "leadsheet"
})
public class LeadsheetsNodeType {

    @XmlElement(required = true)
    protected List<LeadsheetNodeType> leadsheet;
    @XmlAttribute(name = "num")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger num;

    /**
     * Gets the value of the leadsheet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leadsheet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeadsheet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LeadsheetNodeType }
     * 
     * 
     */
    public List<LeadsheetNodeType> getLeadsheet() {
        if (leadsheet == null) {
            leadsheet = new ArrayList<LeadsheetNodeType>();
        }
        return this.leadsheet;
    }

    /**
     * Gets the value of the num property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getNum() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setNum(BigInteger value) {
        this.num = value;
    }

}
