package de.freebits.omt.entity;

// Generated 04.02.2010 15:04:43 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "test")
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = -323535516555968008L;
	
	private Integer id;
	private String firstname;
	private String lastname;

	public Users() {
	}

	public Users(String firstname, String lastname) {
		this.firstname = firstname;
		this.lastname = lastname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false)
	@NotNull
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false)
	@NotNull
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

}
