//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.07 at 10:07:24 AM MEZ 
//


package de.freebits.omt.core.xml.entities.motifextraction;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.freebits.omt.core.xml.entities.motifextraction package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mex_QNAME = new QName("http://freebits.de/OMT-engine/schemas/MotivEXtraction", "mex");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.freebits.omt.core.xml.entities.motifextraction
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChordsType }
     * 
     */
    public ChordsType createChordsType() {
        return new ChordsType();
    }

    /**
     * Create an instance of {@link ValidationNotesType }
     * 
     */
    public ValidationNotesType createValidationNotesType() {
        return new ValidationNotesType();
    }

    /**
     * Create an instance of {@link MelodyType }
     * 
     */
    public MelodyType createMelodyType() {
        return new MelodyType();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link ChordType }
     * 
     */
    public ChordType createChordType() {
        return new ChordType();
    }

    /**
     * Create an instance of {@link PatternsType }
     * 
     */
    public PatternsType createPatternsType() {
        return new PatternsType();
    }

    /**
     * Create an instance of {@link PattersNodeType }
     * 
     */
    public PattersNodeType createPattersNodeType() {
        return new PattersNodeType();
    }

    /**
     * Create an instance of {@link MexType }
     * 
     */
    public MexType createMexType() {
        return new MexType();
    }

    /**
     * Create an instance of {@link ValidationNoteType }
     * 
     */
    public ValidationNoteType createValidationNoteType() {
        return new ValidationNoteType();
    }

    /**
     * Create an instance of {@link ChordsNodeType }
     * 
     */
    public ChordsNodeType createChordsNodeType() {
        return new ChordsNodeType();
    }

    /**
     * Create an instance of {@link MelodyNodeNodeType }
     * 
     */
    public MelodyNodeNodeType createMelodyNodeNodeType() {
        return new MelodyNodeNodeType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link MelodyNodeType }
     * 
     */
    public MelodyNodeType createMelodyNodeType() {
        return new MelodyNodeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://freebits.de/OMT-engine/schemas/MotivEXtraction", name = "mex")
    public JAXBElement<MexType> createMex(MexType value) {
        return new JAXBElement<MexType>(_Mex_QNAME, MexType.class, null, value);
    }

}
